# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 20:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DadosPessoais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50, verbose_name=b'Nome')),
                ('street', models.CharField(max_length=100, verbose_name=b'Endere\xc3\xa7o')),
                ('city', models.CharField(max_length=50, verbose_name=b'Cidade')),
                ('cep', models.CharField(max_length=50, verbose_name=b'Cep')),
                ('phone', models.CharField(max_length=20, verbose_name=b'Telefone')),
                ('moblie', models.CharField(max_length=20, verbose_name=b'Celular')),
                ('about', models.TextField(max_length=255, verbose_name=b'Sobre')),
                ('data_nascimento', models.DateField(default=django.utils.timezone.now, verbose_name=b'Data Nascimento')),
                ('email', models.EmailField(max_length=254, verbose_name=b'Email')),
                ('conhecimentos', models.TextField(max_length=255, verbose_name=b'Conhecimentos')),
                ('github', models.CharField(max_length=100, verbose_name=b'link')),
                ('curse', models.CharField(max_length=100, verbose_name=b'Curso')),
                ('local', models.CharField(max_length=100, verbose_name=b'Local')),
                ('empresa', models.CharField(max_length=100, verbose_name=b'Empresa')),
                ('cargo', models.CharField(max_length=100, verbose_name=b'Cargo')),
                ('resumo', models.TextField(max_length=255, verbose_name=b'Resumo')),
            ],
        ),
    ]
