# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 14:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dadospessoais',
            options={'verbose_name': 'Dados Pessoais', 'verbose_name_plural': 'Dados Pessoais'},
        ),
    ]
