# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-05 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0002_auto_20160603_1413'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dadospessoais',
            old_name='local',
            new_name='actual_job',
        ),
        migrations.RenameField(
            model_name='dadospessoais',
            old_name='street',
            new_name='adress',
        ),
        migrations.RenameField(
            model_name='dadospessoais',
            old_name='moblie',
            new_name='mobile',
        ),
        migrations.RenameField(
            model_name='dadospessoais',
            old_name='Name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='dadospessoais',
            name='cargo',
        ),
        migrations.RemoveField(
            model_name='dadospessoais',
            name='curse',
        ),
        migrations.RemoveField(
            model_name='dadospessoais',
            name='resumo',
        ),
        migrations.AddField(
            model_name='dadospessoais',
            name='current_position',
            field=models.CharField(default='', max_length=100, verbose_name=b'Cargo atual'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dadospessoais',
            name='data_nascimento',
            field=models.DateField(default=b'01 de janeiro de 2000', verbose_name=b'Data Nascimento'),
        ),
        migrations.AlterField(
            model_name='dadospessoais',
            name='github',
            field=models.CharField(max_length=100, verbose_name=b'Github'),
        ),
    ]
