# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-05 18:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0003_auto_20160605_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadospessoais',
            name='data_nascimento',
            field=models.CharField(default=b'01 de janeiro de 2000', max_length=255, verbose_name=b'Data Nascimento'),
        ),
    ]
